/* Malta Camp 2026 · Language toggle (ES / EN) */
(function () {
  const T = {
    /* ── NAV ── */
    'nav.comida-unav':         { es: 'Comida UNAV',         en: 'UNAV Lunch'          },
    'nav.asado-final':         { es: 'Asado Final',         en: 'Final BBQ'           },
    'nav.inventario':          { es: 'Inventario',          en: 'Inventory'           },
    'nav.alergenos':           { es: 'Alérgenos',           en: 'Allergens'           },

    /* ── SHARED ── */
    'friso.label':             { es: 'Cronograma',          en: 'Schedule'            },
    'friso.recogida':          { es: 'Recogida',            en: 'Pack-up'             },
    'sidebar.heading':         { es: 'Secciones',           en: 'Sections'            },
    'meta.day':                { es: 'Día',                 en: 'Day'                 },
    'meta.days':               { es: 'Días',                en: 'Days'                },
    'meta.hour':               { es: 'Hora',                en: 'Time'                },
    'meta.attendees':          { es: 'Asistentes',          en: 'Attendees'           },
    'meta.budget':             { es: 'Presupuesto',         en: 'Budget'              },
    'meta.countries':          { es: 'Países',              en: 'Countries'           },
    'meta.source':             { es: 'Fuente',              en: 'Source'              },
    'meta.status':             { es: 'Estado',              en: 'Status'              },

    /* ── SPANISH NIGHT ── */
    'sn.eyebrow':   { es: 'Evento 01 · Javier, Navarra',  en: 'Event 01 · Javier, Navarre' },
    'sn.desc':      { es: 'Una noche de puestecitos por provincias de España. Los participantes recorren los stands, prueban la gastronomía española y viven una experiencia inmersiva de la cultura del país.',
                      en: 'An evening of stalls representing Spain\'s provinces. Participants go from stand to stand, tasting Spanish gastronomy and living an immersive experience of the country\'s culture.' },
    'sn.meta.day':         { es: 'Lunes 3 agosto',         en: 'Monday 3 August'     },
    'sn.friso.montaje':    { es: 'Montaje puestecitos',    en: 'Stall setup'         },
    'sn.friso.equipo':     { es: 'Equipo asignado: 17 personas', en: 'Assigned team: 17 people' },
    'sn.friso.apertura':   { es: 'Apertura al público',   en: 'Open to public'      },
    'sn.sidebar.provincias': { es: 'Provincias',           en: 'Provinces'           },
    'sn.sidebar.cocina':     { es: 'Cocina',               en: 'Kitchen'             },
    'sn.sidebar.puestecitos': { es: 'Puestecitos',         en: 'Stalls'              },
    'sn.sidebar.pasaporte':  { es: 'Pasaporte',            en: 'Passport'            },
    'sn.sidebar.fun':        { es: 'Para hacerlo fun',     en: 'Making it fun'       },
    'sn.sidebar.cantidades': { es: 'Cantidades y servicio', en: 'Quantities & service' },
    'sn.sec.provincias':   { es: 'Provincias',             en: 'Provinces'           },
    'sn.sec.cocina':       { es: 'Cocina',                 en: 'Kitchen'             },
    'sn.sec.cocina.note':  { es: 'Clasificación por método de cocinado, basada en el producto real de compra (ver <strong>detalle_spanish_night.md</strong>). La mayoría de platos son productos pre-elaborados — solo hay que freír, calentar o emplatar.',
                             en: 'Classification by cooking method, based on actual purchased products. Most dishes are pre-made — just fry, heat or plate up.' },
    'sn.sec.frito':        { es: 'Frito (freidora)',       en: 'Fried (deep fryer)'  },
    'sn.sec.plancha':      { es: 'Plancha / sartén',       en: 'Griddle / pan'       },
    'sn.sec.frio':         { es: 'Frío / sin cocción',     en: 'Cold / no cooking'   },
    'sn.th.plato':         { es: 'Plato',                  en: 'Dish'                },
    'sn.th.producto':      { es: 'Producto real',          en: 'Actual product'      },
    'sn.th.cuando':        { es: 'Cuándo',                 en: 'When'                },
    'sn.th.montaje':       { es: 'Cuándo montar',          en: 'When to plate'       },
    'sn.cocina.material':  { es: '<strong>Material necesario:</strong> 3 freidoras (mínimo), plancha o sartenes grandes, cortador de jamón, aceite de freír (5–6 garrafas de 5 L), aceite de oliva (2–3 L), hieleras para los puestos de frío.',
                             en: '<strong>Equipment needed:</strong> 3 deep fryers (minimum), griddle or large pans, ham slicer, frying oil (5–6 × 5 L), olive oil (2–3 L), cool boxes for cold stalls.' },
    'sn.freidoras.note':   { es: 'Mínimo <strong>3 freidoras en simultáneo</strong> — coordinar zonas y aceite (5–6 garrafas de 5 L doble rendimiento).',
                             en: 'Minimum <strong>3 deep fryers running simultaneously</strong> — coordinate zones and oil (5–6 × 5 L bottles, double use).' },
    'sn.sec.puestecitos':  { es: 'Puestecitos',            en: 'Stalls'              },
    'sn.info.total':       { es: 'Total puestos',          en: 'Total stalls'        },
    'sn.info.estructura':  { es: 'Estructura por puesto',  en: 'Structure per stall' },
    'sn.info.fijacion':    { es: 'Fijación',               en: 'Fastening'           },
    'sn.info.fijacion.v':  { es: 'Tornillos, arandelas, palominas', en: 'Screws, washers, wing nuts' },
    'sn.subsec.vajilla':   { es: 'Vajilla compartida (todos los puestos)', en: 'Shared tableware (all stalls)' },
    'sn.subsec.deco':      { es: 'Decoración puestecitos', en: 'Stall decoration'    },
    'sn.deco.comun':       { es: '<strong>Común a todos:</strong> Rollo Mantel Papel (25 m) · Servilletas burdeos · Banderas CCAA · Pilas AA (16) · Cuerda guirnaldas · Globos helio · Bombona · Rotuladores decoración · Telas decorativas (3 m/caseta)',
                             en: '<strong>Common to all:</strong> Paper tablecloth roll (25 m) · Burgundy napkins · Regional flags · AA batteries (16) · Garland cord · Helium balloons · Canister · Decoration markers · Decorative fabrics (3 m/stall)' },
    'sn.sec.pasaporte':    { es: 'Pasaporte',              en: 'Passport'            },
    'sn.pasaporte.body':   { es: 'Concepto: cada participante recibe un pasaporte impreso y sella en cada puestecito.<br><br><strong>Confirmado:</strong><br>Pasaporte (diseño e impresión) gestionado por Guest Experience.<br><br><strong>Materiales presupuestados:</strong><br>75 sellos customizables (4 €/ud), 75 tintas para sellos (2 €/ud)<br><br><strong style="color:#16a34a">Completado:</strong> Diseño e impresión de sellos lista.',
                             en: 'Concept: each participant receives a printed passport and stamps it at every stall.<br><br><strong>Confirmed:</strong><br>Passport (design and printing) managed by Guest Experience.<br><br><strong>Budgeted materials:</strong><br>75 custom stamps (4 €/ea), 75 stamp inks (2 €/ea)<br><br><strong style="color:#16a34a">Completed:</strong> Stamp design and printing ready.' },
    'sn.sec.fun':          { es: 'Para hacerlo fun',       en: 'Making it fun'       },
    'sn.fun.photo.title':  { es: 'Photomatón',             en: 'Photo Booth'         },
    'sn.fun.photo.canc':   { es: 'Cancelado.',             en: 'Cancelled.'          },
    'sn.fun.pul.title':    { es: 'Pululantes',             en: 'Roaming characters'  },
    'sn.fun.pul.body':     { es: '10 disfraces temáticos confirmados (Don Quijote, Isabel la Católica…).<br>Presupuesto: 45 €/ud × 10 = <strong>450 €</strong>.',
                             en: '10 themed costumes confirmed (Don Quixote, Isabella I…).<br>Budget: 45 €/ea × 10 = <strong>450 €</strong>.' },
    'sn.sec.cantidades':   { es: 'Cantidades y Servicio',  en: 'Quantities & Service' },
    'sn.cant.intro':       { es: '560 personas · post-cena · formato cata por puestos. Target por ítem: <strong>~350 porciones</strong> (60% del aforo).',
                             en: '560 people · post-dinner · tasting-by-stall format. Target per item: <strong>~350 portions</strong> (60% capacity).' },
    'sn.info.prep':        { es: 'Preparación',            en: 'Preparation'         },
    'sn.info.cantidad':    { es: 'Cantidad',               en: 'Quantity'            },
    'sn.info.servicio':    { es: 'Servicio',               en: 'Service'             },
    'sn.subsec.galicia':   { es: 'Galicia y Asturias',     en: 'Galicia & Asturias'  },
    'sn.subsec.pv':        { es: 'País Vasco, Navarra y Cantabria', en: 'Basque Country, Navarre & Cantabria' },
    'sn.subsec.aragon':    { es: 'Aragón, La Rioja y Cataluña', en: 'Aragon, La Rioja & Catalonia' },
    'sn.subsec.madrid':    { es: 'Madrid y Castilla-La Mancha', en: 'Madrid & Castilla-La Mancha' },
    'sn.subsec.castilla':  { es: 'Castilla y León y Extremadura', en: 'Castile & León and Extremadura' },
    'sn.subsec.valencia':  { es: 'Valencia y Murcia',      en: 'Valencia & Murcia'   },
    'sn.subsec.andalucia': { es: 'Andalucía',              en: 'Andalusia'           },
    'sn.subsec.baleares':  { es: 'Baleares, Canarias, Ceuta y Melilla', en: 'Balearics, Canaries, Ceuta & Melilla' },
    'sn.subsec.postres':   { es: 'Postres',                en: 'Desserts'            },
    'sn.subsec.logistica': { es: 'Notas logísticas',       en: 'Logistics notes'     },
    'sn.log.freidoras':    { es: 'Freidoras necesarias',   en: 'Fryers needed'       },
    'sn.log.calientes':    { es: 'Platos calientes',       en: 'Hot dishes'          },
    'sn.log.frios':        { es: 'Platos fríos',           en: 'Cold dishes'         },
    'sn.log.orden':        { es: 'Orden recorrido',        en: 'Circuit order'       },
    'sn.log.freidoras.v':  { es: 'Mínimo <strong>3–4 freidoras en simultáneo</strong>: bocata de calamares · croquetas · patatas bravas · buñuelos',
                             en: 'Minimum <strong>3–4 fryers simultaneously</strong>: squid roll · croquettes · patatas bravas · fritters' },
    'sn.log.calientes.v':  { es: 'Chistorra · Torreznos · Morcilla · Bocata de calamares · Croquetas · Patatas bravas · Buñuelos',
                             en: 'Chistorra sausage · Pork cracklings · Blood sausage · Squid roll · Croquettes · Patatas bravas · Fritters' },
    'sn.log.frios.v':      { es: 'Gazpacho · Crema catalana · Marineras · Gildas',
                             en: 'Gazpacho · Catalan cream · Marineras · Gildas' },
    'sn.log.orden.v':      { es: 'Salados primero. Postres juntos al final del recorrido como remate.',
                             en: 'Savoury first. Desserts together at the end of the circuit as a finale.' },

    /* ── INTERNATIONAL NIGHTS ── */
    'intl.eyebrow':   { es: 'Evento 02 · Javier, Navarra', en: 'Event 02 · Javier, Navarre' },
    'intl.desc':      { es: 'Cada delegación prepara un plato típico de su país. Dos noches con países repartidos. Cada delegación dispone de cocina y presupuesto para frescos.',
                        en: 'Each delegation prepares a traditional dish from their country. Two nights with countries split across them. Each delegation has a kitchen and a budget for fresh produce.' },
    'intl.meta.days.v': { es: 'Miérc. 5 y Viern. 7',      en: 'Wed. 5 & Fri. 7'    },
    'intl.stat.paises': { es: 'Países',                    en: 'Countries'           },
    'intl.stat.wed':    { es: 'Miércoles 5',               en: 'Wednesday 5'         },
    'intl.stat.fri':    { es: 'Viernes 7',                 en: 'Friday 7'            },
    'intl.friso.prep':  { es: 'Preparación cocinas',       en: 'Kitchen prep'        },
    'intl.friso.vol':   { es: '7 voluntarios además de delegaciones', en: '7 volunteers plus delegations' },
    'intl.friso.apertura': { es: 'Apertura puestos',       en: 'Stalls open'         },
    'intl.resp.label':  { es: 'Respuestas formulario',     en: 'Form responses'      },
    'intl.resp.btn':    { es: 'Ver hoja ↗',                en: 'View sheet ↗'        },
    'intl.sidebar.paises': { es: 'Países',                 en: 'Countries'           },
    'intl.sidebar.cocina': { es: 'Material de cocina',     en: 'Kitchen equipment'   },
    'intl.sidebar.form':   { es: 'Formulario delegaciones', en: 'Delegation form'    },
    'intl.sec.paises':  { es: 'Países por día',            en: 'Countries by day'    },
    'intl.utensils.note': { es: 'Todos los utensilios de cocina (cacerolas, sartenes, cuchillos, tablas, espátulas, hornillos de gas) están presupuestados pero <strong>pendientes de confirmar si se pueden reutilizar del equipamiento del Castillo de Javier</strong>.',
                            en: 'All kitchen utensils (pots, pans, knives, boards, spatulas, gas burners) are budgeted but <strong>pending confirmation of whether they can be reused from the Castillo de Javier equipment</strong>.' },
    'intl.th.pais':     { es: 'País',                      en: 'Country'             },
    'intl.th.dia':      { es: 'Día',                       en: 'Day'                 },
    'intl.th.plato':    { es: 'Plato previsto',            en: 'Planned dish'        },
    'intl.th.nota':     { es: 'Nota',                      en: 'Note'                },
    'intl.div.wed':     { es: 'MIÉRCOLES 5 · DÍA 1 — 13 países', en: 'WEDNESDAY 5 · DAY 1 — 13 countries' },
    'intl.div.fri':     { es: 'VIERNES 7 · DÍA 2 — 12 países',   en: 'FRIDAY 7 · DAY 2 — 12 countries'   },
    'intl.sec.cocina':  { es: 'Material de cocina por noche', en: 'Kitchen equipment by night' },
    'intl.cocina.note': { es: '13 de 25 países necesitan cocina — 7 el miércoles, 6 el viernes.',
                          en: '13 of 25 countries need cooking — 7 on Wednesday, 6 on Friday.' },
    'intl.th.material': { es: 'Material',                  en: 'Equipment'           },
    'intl.th.wed':      { es: 'Miércoles 5',               en: 'Wednesday 5'         },
    'intl.th.fri':      { es: 'Viernes 7',                 en: 'Friday 7'            },
    'intl.cook.pots':   { es: 'Ollas / Sartenes',          en: 'Pots / Pans'         },
    'intl.cook.oven':   { es: 'Horno',                     en: 'Oven'                },
    'intl.cook.plancha': { es: 'Planchas eléctricas',      en: 'Electric griddles'   },
    'intl.cook.otras':  { es: 'Otras',                     en: 'Other'               },
    'intl.cook.nofogo': { es: 'Sin fogón / horno',         en: 'No hob / oven'       },
    'intl.cook.total':  { es: 'Países con cocina',         en: 'Countries needing cooking' },
    'intl.basuras':     { es: '<strong>🗑️ Basuras</strong> — Prever cubos de basura tanto en zona de evento (uno por puesto o zona compartida) como en cada cocina. Coordinar vaciado entre noches.',
                          en: '<strong>🗑️ Bins</strong> — Plan for bins in the event area (one per stall or shared zone) and in each kitchen. Coordinate emptying between nights.' },
    'intl.sec.form':    { es: 'Formulario delegaciones',   en: 'Delegation form'     },
    'intl.form.label':  { es: 'Formulario',                en: 'Form'                },
    'intl.form.btn':    { es: 'Formulario enviado ↗',      en: 'Form sent ↗'         },
    'intl.form.resp.label': { es: 'Países contestados',    en: 'Countries responded' },
    'intl.form.resp.pct':   { es: '100% completado ✓',     en: '100% complete ✓'     },
    'intl.form.pct.of':    { es: '/ 25 países',            en: '/ 25 countries'      },
    'intl.form.tbd':    { es: 'Pendiente → Actualizar inventario con Ana una vez sabido el espacio que necesitan.',
                          en: 'Pending → Update inventory with Ana once space requirements are confirmed.' },

    /* Badge text inside country rows */
    'badge.dia1':       { es: 'Día 1 · Miérc. 5',         en: 'Day 1 · Wed. 5'      },
    'badge.dia2':       { es: 'Día 2 · Viern. 7',         en: 'Day 2 · Fri. 7'      },

    /* ── COMIDA UNAV ── */
    'unav.eyebrow':   { es: 'Evento 03 · Universidad de Navarra', en: 'Event 03 · University of Navarre' },
    'unav.title':     { es: 'Comida en la UNAV',           en: 'Lunch at UNAV'       },
    'unav.desc':      { es: 'Comida oficial del camp en la Universidad de Navarra. Servicio de catering externo. Momento de excursión y vínculo con Pamplona.',
                        en: 'Official camp lunch at the University of Navarre. External catering service. An excursion moment and connection with Pamplona.' },
    'unav.meta.day.v':  { es: 'Jueves 6 agosto',          en: 'Thursday 6 August'   },
    'unav.friso.llegada': { es: 'Llegada UNAV',            en: 'Arrive UNAV'         },
    'unav.friso.mesas':   { es: 'Preparación mesas',       en: 'Table setup'         },
    'unav.friso.comida':  { es: 'Comida',                  en: 'Lunch'               },
    'unav.sidebar.catering': { es: 'Catering',             en: 'Catering'            },
    'unav.sidebar.menu':     { es: 'Menú',                 en: 'Menu'                },
    'unav.sec.catering':  { es: 'Catering',                en: 'Catering'            },
    'unav.contact.role':  { es: 'Sodexo · Catering UNAV', en: 'Sodexo · UNAV Catering' },
    'unav.sec.menu':      { es: 'Menú',                    en: 'Menu'                },
    'unav.menu.primero':  { es: 'Primero',                 en: 'First course'        },
    'unav.menu.primero.v': { es: 'Gazpacho o Salmorejo',  en: 'Gazpacho or Salmorejo' },
    'unav.menu.segundo':  { es: 'Segundo',                 en: 'Main course'         },
    'unav.menu.segundo.v': { es: 'Albóndigas en salsa con patatas fritas <span style="font-size:11px;color:var(--gray-400)">60%</span><br>Ensalada de pasta <span style="font-size:11px;color:var(--gray-400)">40%</span>',
                             en: 'Meatballs in sauce with fries <span style="font-size:11px;color:var(--gray-400)">60%</span><br>Pasta salad <span style="font-size:11px;color:var(--gray-400)">40%</span>' },
    'unav.menu.postre':   { es: 'Postre',                  en: 'Dessert'             },
    'unav.menu.postre.v': { es: 'Variedad de lácteos (yogures, natillas, flanes, cuajada…) y fruta <span class="tbd">si pueden</span>',
                            en: 'Variety of dairy (yoghurts, custard, flan, curd…) and fruit <span class="tbd">if possible</span>' },
    'unav.menu.acomp':    { es: 'Acompañamiento',          en: 'Side'                },
    'unav.menu.acomp.v':  { es: 'Pan · Agua · Refrescos', en: 'Bread · Water · Soft drinks' },
    'unav.menu.precio':   { es: 'Precio',                  en: 'Price'               },

    /* ── ASADO FINAL ── */
    'asado.eyebrow':  { es: 'Evento 04 · Javier, Navarra', en: 'Event 04 · Javier, Navarre' },
    'asado.title':    { es: 'Asado Final',                  en: 'Final BBQ'           },
    'asado.desc':     { es: 'El gran cierre del camp. Paella y asado para todos los participantes, con bebidas, postres y ambiente de despedida. El evento más grande en términos de logística y montaje.',
                        en: 'The grand camp finale. Paella for all participants, with drinks, desserts and a farewell atmosphere. The biggest event in terms of logistics and setup.' },
    'asado.meta.day.v': { es: 'Domingo 9 agosto',          en: 'Sunday 9 August'     },
    'asado.friso.montaje': { es: 'Montaje mesas',          en: 'Table setup'         },
    'asado.friso.equipo':  { es: 'Equipo montaje (10)',     en: 'Setup team (10)'     },
    'asado.friso.cena':    { es: 'Cena',                   en: 'Dinner'              },
    'asado.friso.mesas':   { es: 'Servicio mesas (10)',     en: 'Table service (10)'  },
    'asado.friso.turno':   { es: 'Segundoturno 20:00-23:00', en: '2nd shift 20:00-23:00' },
    'asado.sidebar.catering': { es: 'Catering',            en: 'Catering'            },
    'asado.sidebar.aperitivo': { es: 'Aperitivo',          en: 'Starter'             },
    'asado.sidebar.postres':   { es: 'Postres',            en: 'Desserts'            },
    'asado.sidebar.montaje':   { es: 'Montaje',            en: 'Setup'               },
    'asado.sub.menu':     { es: 'Menú',                    en: 'Menu'                },
    'asado.info.menu.label': { es: 'Menú confirmado',      en: 'Confirmed menu'      },
    'asado.info.menu.v':  { es: 'Paella carne · 566 pax · incluye desplazamiento, cocinado, emplatado y menaje · <strong>6,50 €/pax +10% IVA = 4.046,90 €</strong>',
                            en: 'Meat paella · 566 pax · includes travel, cooking, plating and tableware · <strong>6.50 €/pax +10% VAT = 4,046.90 €</strong>' },
    'asado.info.ingr.label': { es: 'Ingredientes paella',  en: 'Paella ingredients'  },
    'asado.info.ingr.v':  { es: 'Pollo · Conejo · Costilla de cerdo · Pimientos · Cebolla · Judía verde · Alcachofa · Guisantes · Arroz',
                            en: 'Chicken · Rabbit · Pork rib · Peppers · Onion · Green beans · Artichoke · Peas · Rice' },
    'asado.info.alt.label': { es: 'Menú alternativo',      en: 'Alternative menu'    },
    'asado.info.alt.v':   { es: 'Necesario solo para <strong>~20 personas</strong> — vegetarianos, veganos y sin cerdo.<br>El resto de restricciones (gluten, marisco, lácteos, frutos secos…) no aplican con estos ingredientes.',
                            en: 'Needed only for <strong>~20 people</strong> — vegetarians, vegans and no-pork.<br>Other restrictions (gluten, seafood, dairy, nuts…) do not apply with these ingredients.' },
    'asado.sub.contacto': { es: 'Contacto',                en: 'Contact'             },
    'asado.sub.bebidas':  { es: 'Bebidas (nosotros)',       en: 'Drinks (us)'         },
    'asado.beb.agua':     { es: 'Agua',                    en: 'Water'               },
    'asado.beb.agua.v':   { es: 'Confirmado y presupuestado', en: 'Confirmed and budgeted' },
    'asado.beb.hielo':    { es: 'Hielo',                   en: 'Ice'                 },
    'asado.beb.hielo.v':  { es: 'Confirmado y presupuestado', en: 'Confirmed and budgeted' },
    'asado.beb.jarras':   { es: 'Jarras',                  en: 'Pitchers'            },
    'asado.beb.jarras.v': { es: 'Pendiente',               en: 'Pending'             },
    'asado.beb.barra':    { es: 'Barra',                   en: 'Bar'                 },
    'asado.beb.barra.v':  { es: 'Montar barra con sobras de la semana (pendiente)', en: 'Set up bar with leftover drinks from the week (pending)' },
    'asado.sec.aperitivo': { es: 'Aperitivo',              en: 'Starter'             },
    'asado.aper.note':    { es: 'Todos los productos del aperitivo son donaciones externas. Los cancelados han sido descartados del plan — el resto está pendiente de confirmar cantidad y formato con cada donante.',
                            en: 'All starter products are external donations. Cancelled ones have been dropped — the rest are pending quantity and format confirmation with each donor.' },
    'asado.th.producto':  { es: 'Producto',                en: 'Product'             },
    'asado.th.cantidad':  { es: 'Cantidad',                en: 'Quantity'            },
    'asado.th.donante':   { es: 'Donante',                 en: 'Donor'               },
    'asado.th.estado':    { es: 'Estado',                  en: 'Status'              },
    'asado.sec.postres':  { es: 'Postres',                 en: 'Desserts'            },
    'asado.sub.hd':       { es: 'Opción preferida · Donación Häagen-Dazs', en: 'Preferred option · Häagen-Dazs donation' },
    'asado.sub.fallback': { es: 'Opción A · Fallback si no hay donación', en: 'Option A · Fallback if no donation' },
    'asado.post.brownie.label': { es: 'Brownie de chocolate', en: 'Chocolate brownie' },
    'asado.post.helado.label':  { es: 'Helado de vainilla',   en: 'Vanilla ice cream' },
    'asado.post.total.label':   { es: 'Total Opción A',       en: 'Total Option A'    },
    'asado.sec.montaje':  { es: 'Montaje',                  en: 'Setup'               },
    'asado.sub.espacio':  { es: 'Organización del espacio',  en: 'Space layout'        },
    'asado.esp.paella':   { es: 'Mesas recogida paella',    en: 'Paella collection tables' },
    'asado.esp.paella.v': { es: 'Mesas largas en zona central. Cola por grupos y delegaciones.', en: 'Long tables in the central area. Queue by groups and delegations.' },
    'asado.esp.bebidas':  { es: 'Puesto bebidas',           en: 'Drinks station'      },
    'asado.esp.bebidas.v': { es: 'Mesa lateral con agua, refrescos e hielo. 4 voluntarios.', en: 'Side table with water, soft drinks and ice. 4 volunteers.' },
    'asado.esp.postres':  { es: 'Postres',                  en: 'Desserts'            },
    'asado.esp.postres.v': { es: 'Puesto separado. Se sirven al terminar el servicio principal.', en: 'Separate station. Served after the main service ends.' },
    'asado.sub.mesas':    { es: 'Mesas',                    en: 'Tables'              },
    'asado.stat.mesas':   { es: 'Mesas redondas',           en: 'Round tables'        },
    'asado.stat.pers':    { es: 'Personas / mesa',          en: 'People / table'      },
    'asado.stat.asist':   { es: 'Asistentes est.',          en: 'Est. attendees'      },
    'asado.mesa.contacto': { es: 'Contacto mesas',          en: 'Tables contact'      },
    'asado.mesa.manteles': { es: 'Manteles',                en: 'Tablecloths'         },
    'asado.mesa.manteles.v': { es: 'Donación tía de César. <strong style="color:#16a34a">Recibidas!</strong>', en: 'Donation from César\'s aunt. <strong style="color:#16a34a">Received!</strong>' },
    'asado.mesa.deco':    { es: 'Decoración',               en: 'Decoration'          },
    'asado.mesa.deco.v':  { es: '· Manteles<br>· Cartelitos santos<br>· Servilletas vichy<br>· Eucalipto? Pendiente Sonso<br><span style="color:var(--red);font-weight:500;display:block;margin-top:0.5rem">Pendiente aún de comprar</span>',
                            en: '· Tablecloths<br>· Saint name cards<br>· Vichy napkins<br>· Eucalyptus? Pending Sonso<br><span style="color:var(--red);font-weight:500;display:block;margin-top:0.5rem">Still pending purchase</span>' },
    'asado.mesa.gala':    { es: 'Qué usar de la Gala Night', en: 'What to reuse from Gala Night' },
    'asado.mesa.gala.v':  { es: '<span class="tbd">revisar inventario — centros, velas…</span>', en: '<span class="tbd">check inventory — centrepieces, candles…</span>' },

    /* ── ALÉRGENOS ── */
    'alg.eyebrow':    { es: 'Referencia · Malta Camp 2026', en: 'Reference · Malta Camp 2026' },
    'alg.title':      { es: 'Alérgenos &amp; Dietas',      en: 'Allergens &amp; Diets' },
    'alg.desc':       { es: 'Restricciones alimentarias declaradas por los participantes. Usar como referencia al cerrar menús con catering y coordinar alternativas.',
                        en: 'Dietary restrictions declared by participants. Use as reference when finalising menus with catering and coordinating alternatives.' },
    'alg.meta.fuente.v': { es: 'Excel dietas UNAV',        en: 'UNAV diets spreadsheet' },
    'alg.meta.estado.v': { es: 'Borrador',                 en: 'Draft'               },
    'alg.stat.criticas': { es: 'Restricciones críticas',   en: 'Critical restrictions' },
    'alg.stat.personas': { es: 'Personas con alguna restricción', en: 'People with a restriction' },
    'alg.stat.total':    { es: 'Asistentes totales',       en: 'Total attendees'     },
    'alg.sec.leyenda':   { es: 'Leyenda de riesgo',        en: 'Risk legend'         },
    'alg.risk.critico':  { es: '🔴 Crítico — reacción severa posible', en: '🔴 Critical — severe reaction possible' },
    'alg.risk.moderado': { es: '🟠 Moderado — requiere alternativa',   en: '🟠 Moderate — alternative required'    },
    'alg.risk.bajo':     { es: '🟡 Bajo — vigilar ingredientes',       en: '🟡 Low — monitor ingredients'          },
    'alg.risk.ok':       { es: '🟢 OK — no aplica en el menú',         en: '🟢 OK — does not apply to the menu'    },
    'alg.sec.restricciones': { es: 'Restricciones por evento',         en: 'Restrictions by event'   },
    'alg.paella.note':   { es: 'Ingredientes paella: <strong>Pollo · Conejo · Costilla de cerdo · Pimientos · Cebolla · Judía verde · Alcachofa · Guisantes · Arroz</strong>',
                           en: 'Paella ingredients: <strong>Chicken · Rabbit · Pork rib · Peppers · Onion · Green beans · Artichoke · Peas · Rice</strong>' },
    'alg.th.restriccion': { es: 'Restricción',             en: 'Restriction'         },
    'alg.th.num':          { es: 'Nº personas',            en: 'No. people'          },
    'alg.th.nivel':        { es: 'Nivel de riesgo',        en: 'Risk level'          },
  };

  window.LANG = localStorage.getItem('mc_lang') || 'es';

  function applyLang(lang) {
    window.LANG = lang;
    localStorage.setItem('mc_lang', lang);
    document.documentElement.lang = lang;

    document.querySelectorAll('[data-i18n]').forEach(el => {
      const key = el.getAttribute('data-i18n');
      if (T[key] && T[key][lang] !== undefined) {
        el.innerHTML = T[key][lang];
      }
    });

    /* update all toggle buttons on the page */
    document.querySelectorAll('.lang-toggle').forEach(btn => {
      btn.textContent = lang === 'es' ? '🇬🇧' : '🇪🇸';
    });
  }

  window.toggleLang = function () {
    applyLang(window.LANG === 'es' ? 'en' : 'es');
  };

  document.addEventListener('DOMContentLoaded', () => applyLang(window.LANG));
})();
